version: '3.8'

networks:
  # Define the network globally
  back-tier:
    driver: bridge

volumes:
  postgres_data:  # store questions ad feedbacks
  grafana_data:  # dashboard
  ollama_data:  # locally phi3 model ~2gb


services:

  # elasticsearch:
  #   image: "docker.elastic.co/elasticsearch/elasticsearch:8.4.3"
  #   container_name: elasticsearch
  #   environment:
  #     - discovery.type=single-node
  #     - xpack.security.enabled=false
  #   ports:
  #     - "9200:9200"
  #     - "9300:9300"
  #   networks:
  #     - back-tier  # Ensure network is correctly referenced


  ollama:
    tty: true
    stdin_open: true
    restart: always
    image: "ollama/ollama:latest"
    container_name: ollama
    pull_policy: always
    volumes:
      - ollama_data:/root/.ollama  # put downloaded models
      - ./ollama_init/entrypoint.sh:/root/entrypoint.sh  # script serve and pull phi3 model ~3-4 min
    ports:
      - "11434:11434"
    networks:
      - back-tier  # Ensure network is correctly referenced
    entrypoint: ["/usr/bin/bash", "/root/entrypoint.sh"]  # script serve and pull phi3 model ~3-4 min
    # healthcheck:
    #   # test: ["CMD", "curl", "-f", "http://localhost:11434/api/tags"]
    #   test: ["CMD", "curl", "-f", "http://localhost:11434/"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 30
    #   start_period: 60s
    # https://ollama.com/library/phi3


  postgres:
    restart: unless-stopped
    image: "postgres:latest"
    container_name: postgres
    env_file:
      - .env
    # environment:
    #   POSTGRES_DB: ${POSTGRES_DB}
    #   POSTGRES_HOST: ${POSTGRES_HOST}
    #   POSTGRES_USER: "${POSTGRES_USER:-admin}"
    #   POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-admin}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # See: https://gist.github.com/onjin/2dd3cc52ef79069de1faa2dfd456c945
      - ./postgres_init:/docker-entrypoint-initdb.d
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    networks:
      - back-tier  # Ensure network is correctly referenced
    healthcheck:
      # test: ["CMD-SHELL", "pg_isready -U user"]
      test: ["CMD-SHELL", "pg_isready -U admin -d media_assistant"]
      interval: 5s
      timeout: 5s
      retries: 5
  
  
  adminer:
    restart: unless-stopped
    image: "adminer:latest"
    container_name: "adminer"
    env_file:
      - .env
    # environment:
    #   ADMINER_PORT: "${ADMINER_PORT:-9002}"
    ports:
      ## External Access: Used to specify port mappings between the Docker host and the container.
      ## "<host_port>:<container_port>"
      - "${ADMINER_PORT:-8080}:8080"
    networks:
      - "back-tier"
    depends_on:
      - postgres


  grafana:
    restart: unless-stopped
    image: "grafana/grafana:latest"
    container_name: grafana
    # Host specifics
    # hostname: ${HOSTNAME:-services}
    # User ID and Group ID
    user: "${PUID:-472}:${PGID:-0}"  # for load custom grafana.ini config file in docker-compose
    env_file:
      # https://grafana.com/docs/grafana/latest/setup-grafana/configure-docker/
      - .env
    environment:
      # GF_SECURITY_ADMIN_USER: admin
      # GF_SECURITY_ADMIN_PASSWORD: admin
      # GF_PATHS_CONFIG: "/etc/grafana/grafana.ini"
      # GF_PATHS_DATA: /var/lib/grafana
      # GF_PATHS_HOME: /usr/share/grafana
      # GF_PATHS_LOGS: /var/log/grafana
      # GF_PATHS_PLUGINS: /var/lib/grafana/plugins
      # GF_PATHS_PROVISIONING: /etc/grafana/provisioning
      # HOME: /home/grafana
      GF_SECURITY_ADMIN_USER: "${GRAFANA_ADMIN_USER:-admin}"
      GF_SECURITY_ADMIN_PASSWORD: "${GRAFANA_ADMIN_PASSWORD:-admin}"
      GF_SECURITY_SECRET_KEY: "${GRAFANA_SECRET_KEY:-SECRET_KEY}"
      GF_SECURITY_ALLOW_EMBEDDING: "true"
      GF_AUTH_ANONYMOUS_ENABLED: "false"
      # GF_AUTH_ANONYMOUS_ORG_ROLE: Viewer  # 'Editor' deprecated only viewer role
      GF_USERS_ALLOW_SIGN_UP: "false"
      GF_USERS_ALLOW_ORG_CREATE: "false"
    volumes:
      # Optional: Persist Grafana data (users, settings, plugins, etc.)
      - "grafana_data:${GF_PATHS_DATA:-/var/lib/grafana}:rw"
      # Actual dashboards JSON directory (exported dashboards go here)
      # Maps a local file to a file inside the container, and makes it read-only
      - "./grafana/dashboards/dashboards.json:${GF_PATHS_HOME:-/usr/share/grafana}/dashboards/dashboards.json:ro"  # your exported dashboards
      # Provisioning configs (dashboards + datasources.yaml)
      # https://grafana.com/docs/grafana/latest/administration/provisioning/
      - "./grafana/provisioning/dashboards/dashboards.yaml:${GF_PATHS_PROVISIONING:-/etc/grafana/provisioning}/dashboards/dashboards.yaml:ro"  # defines dashboards provider
      - "./grafana/provisioning/datasources/datasources.yaml:${GF_PATHS_PROVISIONING:-/etc/grafana/provisioning}/datasources/datasources.yaml:ro"  # defines datasources
      - "./grafana/custom.ini:${GF_PATHS_CONFIG:-/etc/grafana/grafana.ini}"  # provisioning = true
    ports:
      - "3000:3000"
    networks:
      - back-tier  # Ensure network is correctly referenced
    depends_on:
      - postgres
    # entrypoint: [ "sh", "-c", "grafana-server & sleep 10 && python3 /init.py && wait" ]
    # entrypoint: >-
    #   sh -c "
    #     grafana-server --homepath=/usr/share/grafana & 
    #     sleep 10 &&
    #     python /init.py &&
    #     wait
    #   "


  app:
    build:
      context: .   # Flask/FastAPI
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - FLASK_ENV=development
    #   POSTGRES_HOST: postgres  # Ensure POSTGRES_HOST points to the service name
    #   POSTGRES_DB: ${POSTGRES_DB}
    #   POSTGRES_USER: ${POSTGRES_USER}
    #   POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    #   OPENAI_API_KEY: ${OPENAI_API_KEY}
    #   DATA_PATH: "Data/documents-with-ids.json"
    ports:
      - "${APP_PORT:-5000}:5000"
    networks:
      - back-tier  # Ensure network is correctly referenced
    depends_on:
      - ollama
      - postgres
